{% set name = "aws-cdk.aws-sns-subscriptions" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-sns-subscriptions-{{ version }}.tar.gz
  sha256: f653af8f2209a0a7146d62eef778a404214f6da120b0374790d92f3aee875210

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.aws-kms ==1.204.0
    - aws-cdk.aws-lambda ==1.204.0
    - aws-cdk.aws-sns ==1.204.0
    - aws-cdk.aws-sqs ==1.204.0
    - aws-cdk.core ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_sns_subscriptions
    - aws_cdk.aws_sns_subscriptions._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: CDK Subscription Constructs for AWS SNS
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
